// Package backend bootstraps the optional API server (Phase 4+ of the build
// plan). The CLI — the v1 product — does not import it and never needs it
// running (Phase 2.1: the CLI must stay fully useful with zero backend,
// forever).
//
// Three listeners, mirroring the split the reference project
// uses:
//
//	gRPC   127.0.0.1:8090  internal only; the gateway dials it over loopback
//	HTTP   :8080           public REST/JSON, generated by grpc-gateway
//	admin  127.0.0.1:8081  health and runtime log level, never public
//
// One process, not three services. Phase 5.1 is explicit that this is a single
// small Go service and splitting it would have no justification at this scale.
package backend

import (
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log/slog"
	"net"
	"net/http"
	"os/signal"
	"syscall"

	gwruntime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/grpclog"

	"github.com/dhyaneshsiddhartha15/DeployIQ/api/swagger"
	"github.com/dhyaneshsiddhartha15/DeployIQ/pkg/config"
	"github.com/dhyaneshsiddhartha15/DeployIQ/pkg/constants"
	"github.com/dhyaneshsiddhartha15/DeployIQ/pkg/middleware"
	"github.com/dhyaneshsiddhartha15/DeployIQ/pkg/version"
)

// Server owns every long-lived resource the API process holds. Constructed by
// New, driven by Run, and torn down in one place by shutdown.
type Server struct {
	cfg *config.Config

	grpc  *grpc.Server
	http  *http.Server
	admin *http.Server

	// gwConn is the gateway's loopback connection to the gRPC server.
	gwConn *grpc.ClientConn
}

// New builds the server from cfg. It binds nothing and dials nothing — that is
// Run's job — so a construction failure cannot leave a listener open.
func New(cfg *config.Config) (*Server, error) {
	redirectGRPCLog()

	s := &Server{cfg: cfg}

	// Interceptor order is outermost-first. Recovery must lead so it also
	// catches a panic raised inside another interceptor; logging must trail
	// so its duration measures the handler, not the chain.
	s.grpc = grpc.NewServer(
		grpc.ChainUnaryInterceptor(
			middleware.UnaryRecovery,
			middleware.UnaryLogging,
		),
		grpc.ChainStreamInterceptor(
			middleware.StreamRecovery,
			middleware.StreamLogging,
		),
	)

	registerServices(s.grpc)

	s.admin = &http.Server{
		Addr:              cfg.Server.AdminAddr,
		Handler:           adminMux(),
		ReadHeaderTimeout: cfg.Server.ReadHeaderTimeout,
	}
	return s, nil
}

// Run starts every listener and blocks until the context is cancelled, SIGINT
// or SIGTERM arrives, or a listener fails. It always shuts down cleanly before
// returning.
func (s *Server) Run(ctx context.Context) error {
	ctx, stop := signal.NotifyContext(ctx, syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	slog.Info("starting api server",
		slog.String("service", constants.ServiceName),
		slog.String("version", version.String()),
	)

	lis, err := net.Listen("tcp", s.cfg.Server.GRPCAddr)
	if err != nil {
		return fmt.Errorf("backend: listening on %s: %w", s.cfg.Server.GRPCAddr, err)
	}

	// Buffered for every goroutine below, so a failing listener can report
	// and exit without blocking on a receiver that may already be gone.
	errCh := make(chan error, 3)

	go func() {
		slog.Info("serving grpc", slog.String("addr", s.cfg.Server.GRPCAddr))
		if err := s.grpc.Serve(lis); err != nil && !errors.Is(err, grpc.ErrServerStopped) {
			errCh <- fmt.Errorf("grpc server: %w", err)
		}
	}()

	go func() {
		slog.Info("serving admin", slog.String("addr", s.cfg.Server.AdminAddr))
		if err := s.admin.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			errCh <- fmt.Errorf("admin server: %w", err)
		}
	}()

	if err := s.startGateway(); err != nil {
		s.shutdown()
		return err
	}
	go func() {
		slog.Info("serving http", slog.String("addr", s.cfg.Server.HTTPAddr))
		if err := s.http.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			errCh <- fmt.Errorf("http server: %w", err)
		}
	}()

	select {
	case <-ctx.Done():
		slog.Info("shutdown signal received")
	case err := <-errCh:
		slog.Error("listener failed", slog.String("error", err.Error()))
		s.shutdown()
		return err
	}

	s.shutdown()
	return nil
}

// redirectGRPCLog routes gRPC's and grpc-gateway's own logging into slog.
//
// Both write to grpclog, which defaults to plain text on stderr — a request to
// an unrouted path emits "ERROR: Failed to extract ServerMetadata from context"
// in a stream that is otherwise JSON, and the hosting platform's log viewer
// cannot parse it (Phase 8.5).
//
// Only errors are kept. NewLoggerV2's writers are cumulative — an error is
// written to the info, warning *and* error writers — so wiring all three to
// slog turns every gRPC error into three identical records, which would treble
// the error rate Phase 12.1 alerts on. Discarding the first two collapses that
// back to one record at the right level.
//
// The cost is that gRPC's own warnings are dropped along with its very chatty
// info stream (a connectivity state change per event). Acceptable for a
// single-instance service whose gRPC hop is loopback-only; the upgrade path, if
// a gRPC warning ever matters, is a small LoggerV2 implementation that maps
// each severity independently instead of this constructor.
func redirectGRPCLog() {
	errorW := slog.NewLogLogger(slog.Default().Handler(), slog.LevelError).Writer()
	grpclog.SetLoggerV2(grpclog.NewLoggerV2(io.Discard, io.Discard, errorW))
}

// startGateway dials the gRPC server over loopback and builds the public
// REST/JSON handler in front of it.
func (s *Server) startGateway() error {
	// passthrough:// keeps grpc from attempting DNS resolution on an address
	// that is already a host:port.
	conn, err := grpc.NewClient(
		"passthrough:///"+s.cfg.Server.GRPCAddr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	if err != nil {
		return fmt.Errorf("backend: dialling grpc server: %w", err)
	}
	conn.Connect()
	s.gwConn = conn

	gwmux := gwruntime.NewServeMux()
	if err := registerGateways(context.Background(), gwmux, conn); err != nil {
		conn.Close()
		return err
	}

	mux := http.NewServeMux()
	mux.Handle(constants.APIPathPrefix+"/", gwmux)

	if docs, err := swaggerHandler(); err != nil {
		// Missing docs must not stop the API from serving. Phase 4.5 is
		// the contract; the bundle is a convenience on top of it.
		slog.Warn("openapi documentation unavailable", slog.String("error", err.Error()))
	} else {
		mux.Handle("/swagger/", http.StripPrefix("/swagger/", docs))
	}

	s.http = &http.Server{
		Addr:              s.cfg.Server.HTTPAddr,
		Handler:           mux,
		ReadHeaderTimeout: s.cfg.Server.ReadHeaderTimeout,
	}
	return nil
}

// swaggerHandler serves the embedded OpenAPI bundle.
func swaggerHandler() (http.Handler, error) {
	sub, err := fs.Sub(swagger.OpenAPI, "OpenAPI")
	if err != nil {
		return nil, fmt.Errorf("backend: opening embedded openapi bundle: %w", err)
	}
	return http.FileServer(http.FS(sub)), nil
}

// shutdown closes everything in one place, bounded by the configured timeout so
// a wedged connection cannot hold the process open indefinitely.
func (s *Server) shutdown() {
	ctx, cancel := context.WithTimeout(context.Background(), s.cfg.Server.ShutdownTimeout)
	defer cancel()

	// HTTP first: stop accepting new public requests before removing the
	// gRPC backend they depend on.
	if s.http != nil {
		if err := s.http.Shutdown(ctx); err != nil {
			slog.Error("http server shutdown", slog.String("error", err.Error()))
		}
	}
	if err := s.admin.Shutdown(ctx); err != nil {
		slog.Error("admin server shutdown", slog.String("error", err.Error()))
	}

	stopped := make(chan struct{})
	go func() {
		s.grpc.GracefulStop()
		close(stopped)
	}()
	select {
	case <-stopped:
	case <-ctx.Done():
		slog.Warn("grpc graceful stop timed out, forcing")
		s.grpc.Stop()
	}

	if s.gwConn != nil {
		if err := s.gwConn.Close(); err != nil {
			slog.Error("gateway connection close", slog.String("error", err.Error()))
		}
	}

	slog.Info("api server stopped")
}
